/**
Copyright (c) 2018 Clipsey (clipseypone@gmail.com)

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module ppc.types;
public import ppc.types.audio;
public import ppc.types.font;
public import ppc.types.image;
public import ppc.types.model;
public import ppc.types.script;
public import ppc.types.shader;

import ppc.backend.cfile;
import ppc.backend.signatures;

/// The types available to ppc
public enum Types : ubyte {
    Audio,
    Font,
    Image,
    Model,
    Script,
    Shader,
    Raw,


    Undecisive = 255
}

public Types fileSigToType(MemFile mf) {
    if (mf.hasSignature(FileSignature.AudioOGG) || 
        mf.hasSignature(FileSignature.AudioWAV))
            return Types.Audio;
    if (mf.hasSignature(FileSignature.ImageBMP) || 
        mf.hasSignature(FileSignature.ImagePNG) ||
        mf.hasSignature(FileSignature.ImagePTI))
            return Types.Image;
    if (mf.hasSignature(FileSignature.ShaderPSGL))
            return Types.Shader;
    return Types.Undecisive;
}

public Types fileExtToType(string filename) {
    import std.path : extension;

    switch(filename.extension) {
        case ".wav":
        case ".ogg":
        case ".pcm":
            return Types.Audio;

        case ".png":
        case ".tga":
        case ".pti":
        case ".bmp":
            return Types.Image;

        case ".vsh":
        case ".fsh":
        case ".gsh":
            return Types.Shader;

        case ".fbx":
        case ".obj":
            return Types.Model;
            
        default:
            return Types.Raw;
    }
}

public Types getTypeOf(string filename) {
    import std.stdio;
    import std.conv;
    MemFile mf = loadFile(filename);
    Types ts = fileSigToType(mf);
    return (ts == Types.Undecisive) ? fileExtToType(filename) : ts;
}