/**
Copyright (c) 2018 Clipsey (clipseypone@gmail.com)

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module ppc.types.shader;
import ppc.backend.loaders.shader.ppsl;
import ppc.backend.loaders.shader.psgl;
import ppc.backend;
import ppc.backend.cfile;

public enum ShaderType {
    Compiled,
    Fragment,
    Vertex,
    Geometry,
    Tesselation,
    Compute,
}

/// A GLSL shader
public struct GLSLShader {
public:
    /// The shader code
    ubyte[] code;

    string toString() {
        return cast(string)code;
    }
}

public struct Shader {
public:
    /// List of shaders for this bundle
    GLSLShader[ShaderType] shaders;

}

import std.path;
/// Tests the file extension of input file to determine shader type.
ShaderType toShaderType(string input) {
    switch(input.extension) {
        case ".vsh":
        case ".vert":
            return ShaderType.Vertex;
        case ".fsh":
        case ".frag":
            return ShaderType.Fragment;
        case ".geom":
        case ".gsh":
            return ShaderType.Geometry;
        case ".tsh":
        case ".tesc":
        case ".tese":
            return ShaderType.Tesselation;
        case ".csh":
        case ".comp":
            return ShaderType.Compute;
        case ".spv":
        case ".sprv":
            return ShaderType.Compiled;
        default:
            throw new Exception("Invalid shader type!");
    }
}